#!/bin/sh
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Frank Secilia

set -eu
case "${1-}" in
    --target=*) ;;
    *)
        echo "cross compiler wrapper: missing --target= compiler argument" >&2
        exit 97
        ;;
esac
shift
exec cc "$@"
