# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Frank Secilia

include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/common.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/arguments.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/file_api.cmake")

# Maps a path relative to one possible projection base, or returns no destination.
function(_kontra_destination_within path base prefix allow_root context out_destination)
    _kontra_path_within("${base}" "${path}" within relative)
    if(NOT within OR (NOT allow_root AND relative STREQUAL ""))
        set("${out_destination}" "" PARENT_SCOPE)
        return()
    endif()

    if(relative STREQUAL "")
        set(destination "${prefix}")
    else()
        set(destination "${prefix}/${relative}")
    endif()
    _kontra_validate_relative_path("${destination}" "${context}")
    set("${out_destination}" "${destination}" PARENT_SCOPE)
endfunction()

# Maps one declared source file or include directory to a stable path in the detached projection. A source belongs to
# a target, so that target supplies its root. An include directory does not belong to a target, so it may itself be a
# projection root.
function(_kontra_projected_destination
    project encoded_configuration path projection_root owner_target kind target_order out_destination
)
    if(kind STREQUAL "source")
        set(context "source '${path}'")
        set(allow_root FALSE)
    elseif(kind STREQUAL "include")
        set(context "include directory '${path}'")
        set(allow_root TRUE)
    else()
        _kontra_fail(internal-error "unknown projected destination kind '${kind}'")
    endif()

    _kontra_file_api_property("${project}" "${encoded_configuration}" SOURCE_ROOT codemodel_source_root)
    _kontra_file_api_property("${project}" "${encoded_configuration}" BUILD_ROOT codemodel_build_root)

    # The nested binary tree is generated by Kontraband, even when the outer build directory is inside PROJECTION_ROOT.
    _kontra_destination_within(
        "${path}" "${codemodel_build_root}" generated "${allow_root}" "${context}" destination
    )
    if(NOT destination STREQUAL "")
        set("${out_destination}" "${destination}" PARENT_SCOPE)
        return()
    endif()
    _kontra_destination_within("${path}" "${projection_root}" projection "${allow_root}" "${context}" destination)
    if(NOT destination STREQUAL "")
        set("${out_destination}" "${destination}" PARENT_SCOPE)
        return()
    endif()
    _kontra_destination_within(
        "${path}" "${codemodel_source_root}" components "${allow_root}" "${context}" destination
    )
    if(NOT destination STREQUAL "")
        set("${out_destination}" "${destination}" PARENT_SCOPE)
        return()
    endif()

    # Outside the nested project roots, try the target being exported first. For shared paths, then use the most
    # specific target root that contains the path.
    if(NOT owner_target STREQUAL "")
        _kontra_target_bases("${project}" "${encoded_configuration}" "${owner_target}" owner_source owner_build)
        _kontra_destination_within(
            "${path}" "${owner_source}" "components/${owner_target}" "${allow_root}" "${context}" destination
        )
        if(NOT destination STREQUAL "")
            set("${out_destination}" "${destination}" PARENT_SCOPE)
            return()
        endif()
        _kontra_destination_within(
            "${path}" "${owner_build}" "generated/${owner_target}" "${allow_root}" "${context}" destination
        )
        if(NOT destination STREQUAL "")
            set("${out_destination}" "${destination}" PARENT_SCOPE)
            return()
        endif()
    endif()

    # Otherwise use the most specific reachable target root that contains the path.
    set(best_length -1)
    unset(best_destination)
    unset(best_target)
    foreach(target IN LISTS target_order)
        if(target STREQUAL owner_target)
            continue()
        endif()
        _kontra_target_bases("${project}" "${encoded_configuration}" "${target}" target_source target_build)
        foreach(base_kind IN ITEMS source build)
            if(base_kind STREQUAL "source")
                set(base "${target_source}")
                set(prefix "components/${target}")
            else()
                set(base "${target_build}")
                set(prefix "generated/${target}")
            endif()
            _kontra_destination_within("${path}" "${base}" "${prefix}" "${allow_root}" "${context}" candidate)
            if(candidate STREQUAL "")
                continue()
            endif()
            string(LENGTH "${base}" length)
            if(length GREATER best_length)
                set(best_length "${length}")
                set(best_destination "${candidate}")
                set(best_target "${target}")
            elseif(length EQUAL best_length AND NOT candidate STREQUAL best_destination)
                _kontra_fail(
                    ambiguous-projection
                    "${context} maps equally to targets '${best_target}' and '${target}'"
                )
            endif()
        endforeach()
    endforeach()

    if(NOT DEFINED best_destination)
        _kontra_fail(
            unprojected-path
            "${context} is outside PROJECTION_ROOT and every reachable target source/build directory"
        )
    endif()
    set("${out_destination}" "${best_destination}" PARENT_SCOPE)
endfunction()

# Rejects source languages that cannot be represented in the Kbuild projection.
function(_kontra_validate_source_language language)
    if(NOT language STREQUAL "C" AND NOT language STREQUAL "CXX" AND NOT language STREQUAL "ASM")
        _kontra_fail(unsupported-source-language "compiled source uses unsupported CMake language '${language}'")
    endif()
endfunction()

# Describes one CMake source language supported by the Kbuild projection.
function(_kontra_source_language_info language out_name out_extensions out_flag_variable out_suffix_requirement)
    _kontra_validate_source_language("${language}")
    if(language STREQUAL "C")
        set(name "C")
        set(extensions ".c")
        set(flag_variable "CFLAGS")
        set(suffix_requirement "must use the .c suffix")
    elseif(language STREQUAL "CXX")
        set(name "C++")
        set(extensions ".cc;.cpp;.cxx")
        set(flag_variable "KONTRA_CXXFLAGS")
        set(suffix_requirement "must use .cc, .cpp, or .cxx")
    else()
        set(name "ASM")
        set(extensions ".S")
        set(flag_variable "AFLAGS")
        set(suffix_requirement "must use the .S suffix")
    endif()

    set("${out_name}" "${name}" PARENT_SCOPE)
    set("${out_extensions}" "${extensions}" PARENT_SCOPE)
    set("${out_flag_variable}" "${flag_variable}" PARENT_SCOPE)
    set("${out_suffix_requirement}" "${suffix_requirement}" PARENT_SCOPE)
endfunction()

# Rejects compile-group features that Kontraband cannot translate to Kbuild.
function(_kontra_validate_compile_groups target_json_variable)
    _kontra_json_optional_indices(group_indices "${target_json_variable}" compileGroups)
    foreach(group_index IN LISTS group_indices)
        _kontra_json_get(group "${target_json_variable}" compileGroups "${group_index}")
        _kontra_json_optional_length(precompile_header_count group precompileHeaders)
        if(precompile_header_count GREATER 0)
            _kontra_fail(
                unsupported-precompiled-header
                "CMake precompiled headers are not supported for kernel compilation"
            )
        endif()
    endforeach()
endfunction()

# Returns the compiler flags CMake initialized for one language and configuration in the nested toolchain.
function(_kontra_compiler_baseline_tokens project encoded_configuration language out_tokens)
    _kontra_target_property("${project}" KONTRA_KERNEL_PROJECT_COMPILER_BASELINE_DIRECTORY baseline_directory)
    _kontra_decode_configuration("${encoded_configuration}" configuration ignored_configuration_directory)
    string(SHA256 configuration_hash "${configuration}")
    set(path "${baseline_directory}/${language}-${configuration_hash}.txt")
    if(NOT EXISTS "${path}")
        _kontra_fail(
            internal-error
            "nested compiler baseline for language '${language}' and configuration '${configuration}' was not captured"
        )
    endif()
    file(READ "${path}" baseline)
    separate_arguments(tokens UNIX_COMMAND "${baseline}")
    set("${out_tokens}" "${tokens}" PARENT_SCOPE)
endfunction()

# Converts one File API compile group to Kbuild flags and projected include paths.
function(_kontra_compile_group
    project encoded_configuration target_json_variable group_index projection_root target_order
    out_language out_flags out_discarded_options
)
    _kontra_json_get(group "${target_json_variable}" compileGroups "${group_index}")
    _kontra_json_get(language group language)
    _kontra_file_api_property("${project}" "${encoded_configuration}" SOURCE_ROOT codemodel_source_root)
    _kontra_json_get(target_source_path "${target_json_variable}" paths source)
    cmake_path(
        ABSOLUTE_PATH target_source_path
        BASE_DIRECTORY "${codemodel_source_root}"
        NORMALIZE
        OUTPUT_VARIABLE target_source_path
    )
    _kontra_validate_source_language("${language}")

    set(flags)
    set(discarded_options)
    _kontra_compiler_baseline_tokens("${project}" "${encoded_configuration}" "${language}" baseline_tokens)
    _kontra_json_optional_indices(include_indices group includes)
    foreach(index IN LISTS include_indices)
        _kontra_json_get(record group includes "${index}")
        _kontra_json_get(path record path)
        cmake_path(
            ABSOLUTE_PATH path
            BASE_DIRECTORY "${target_source_path}"
            NORMALIZE
            OUTPUT_VARIABLE path
        )
        _kontra_projected_destination(
            "${project}" "${encoded_configuration}" "${path}" "${projection_root}" "" include "${target_order}" destination
        )
        _kontra_json_optional_get(system record isSystem)
        if(system)
            _kontra_quote_shell_argument("-isystem" "system include option" option)
            _kontra_quote_make_argument("$(src)/${destination}" "system include path" include_path)
            list(APPEND flags "${option}" "${include_path}")
        else()
            _kontra_quote_make_argument("-I$(src)/${destination}" "include option" option)
            list(APPEND flags "${option}")
        endif()
    endforeach()

    _kontra_json_optional_indices(definition_indices group defines)
    foreach(index IN LISTS definition_indices)
        _kontra_json_get(record group defines "${index}")
        _kontra_json_get(definition record define)
        _kontra_quote_shell_argument("-D${definition}" "compile definition" option)
        list(APPEND flags "${option}")
    endforeach()

    _kontra_json_optional_indices(fragment_indices group compileCommandFragments)
    foreach(index IN LISTS fragment_indices)
        _kontra_json_get(record group compileCommandFragments "${index}")
        _kontra_json_get(fragment record fragment)
        _kontra_record_backtrace_command("${target_json_variable}" record declaration_command)
        separate_arguments(tokens UNIX_COMMAND "${fragment}")
        foreach(token IN LISTS tokens)
            if(declaration_command STREQUAL "" AND NOT token MATCHES "^-std=")
                list(FIND baseline_tokens "${token}" baseline_index)
                if(NOT baseline_index EQUAL -1)
                    list(REMOVE_AT baseline_tokens "${baseline_index}")
                    continue()
                endif()
                list(APPEND discarded_options "${token}")
                continue()
            endif()
            _kontra_quote_shell_argument("${token}" "compile option" option)
            list(APPEND flags "${option}")
        endforeach()
    endforeach()

    set("${out_language}" "${language}" PARENT_SCOPE)
    set("${out_flags}" "${flags}" PARENT_SCOPE)
    set("${out_discarded_options}" "${discarded_options}" PARENT_SCOPE)
endfunction()

# Updates the development projection so its symlinks point at the current source files.
function(_kontra_ensure_symlink source destination)
    get_filename_component(parent "${destination}" DIRECTORY)
    file(MAKE_DIRECTORY "${parent}")
    if(IS_SYMLINK "${destination}")
        file(READ_SYMLINK "${destination}" existing)
        if(existing STREQUAL "${source}")
            return()
        endif()
        file(REMOVE "${destination}")
    elseif(EXISTS "${destination}")
        _kontra_fail(
            workspace-path-collision
            "workspace source path '${destination}' is occupied by a non-symlink path"
        )
    endif()
    file(CREATE_LINK "${source}" "${destination}" SYMBOLIC)
endfunction()

# Removes empty parent directories after deleting a stale projection symlink, stopping at the workspace root.
function(_kontra_remove_empty_parent_directories path root)
    get_filename_component(directory "${path}" DIRECTORY)
    while(NOT directory STREQUAL "${root}")
        _kontra_path_within("${root}" "${directory}" within ignored)
        if(NOT within)
            return()
        endif()
        file(GLOB children LIST_DIRECTORIES TRUE "${directory}/*")
        if(children)
            return()
        endif()
        file(REMOVE_RECURSE "${directory}")
        get_filename_component(directory "${directory}" DIRECTORY)
    endwhile()
endfunction()

# Removes stale files from the projection without touching files Kontraband did not create.
function(_kontra_refresh_owned_files state_file workspace owned_files)
    set(previous)
    if(EXISTS "${state_file}")
        file(READ "${state_file}" previous_text)
        string(REGEX REPLACE "\n$" "" previous_text "${previous_text}")
        if(NOT previous_text STREQUAL "")
            # Manifest paths have already been validated, so ';' cannot occur in a path and newline is only a separator.
            # Update this code if _kontra_validate_relative_path() changes that rule.
            string(REPLACE "\n" ";" previous "${previous_text}")
        endif()
    endif()
    set(stale "${previous}")
    if(owned_files)
        list(REMOVE_ITEM stale ${owned_files})
    endif()
    foreach(path IN LISTS stale)
        _kontra_validate_relative_path("${path}" "private workspace state")
        if(IS_SYMLINK "${workspace}/${path}")
            file(REMOVE "${workspace}/${path}")
        elseif(EXISTS "${workspace}/${path}")
            _kontra_fail(
                workspace-path-collision
                "stale workspace source path '${workspace}/${path}' is occupied by a non-symlink path"
            )
        endif()
        _kontra_remove_empty_parent_directories("${workspace}/${path}" "${workspace}")
    endforeach()

    set(sorted "${owned_files}")
    list(REMOVE_DUPLICATES sorted)
    list(SORT sorted)
    if(sorted)
        list(JOIN sorted "\n" content)
        string(APPEND content "\n")
    else()
        set(content)
    endif()
    _kontra_write_if_different("${state_file}" "${content}")
endfunction()

# Records one source-to-destination mapping and rejects a conflicting mapping.
function(_kontra_claim_file source destination sources_variable destinations_variable)
    set(sources "${${sources_variable}}")
    set(destinations "${${destinations_variable}}")

    list(FIND destinations "${destination}" claim_index)
    if(claim_index EQUAL -1)
        list(APPEND sources "${source}")
        list(APPEND destinations "${destination}")
    else()
        list(GET sources "${claim_index}" existing_source)
        if(NOT existing_source STREQUAL "${source}")
            _kontra_fail(
                projection-path-collision
                "projection path '${destination}' is claimed by '${existing_source}' and '${source}'"
            )
        endif()
    endif()

    set("${sources_variable}" "${sources}" PARENT_SCOPE)
    set("${destinations_variable}" "${destinations}" PARENT_SCOPE)
endfunction()

# Exports one resolved CMake object graph into a complete Kbuild development workspace.
function(_kontra_export_module
    project encoded_configuration module output_name workspace state_file
    out_sources out_destinations out_discarded_options
)
    _kontra_target_property("${project}" KONTRA_KERNEL_PROJECT_PROJECTION_ROOT projection_root)
    _kontra_optional_target_property("${project}" KONTRA_KERNEL_PROJECT_KBUILD_INCLUDE kbuild_include)
    _kontra_optional_target_property("${project}" KONTRA_KERNEL_PROJECT_KBUILD_ARGUMENTS kbuild_arguments)
    _kontra_object_target_order("${project}" "${encoded_configuration}" "${module}" order)

    file(MAKE_DIRECTORY "${workspace}")
    set(file_sources)
    set(file_destinations)
    set(objects)
    set(flag_lines)
    set(discarded_options)
    _kontra_file_api_property("${project}" "${encoded_configuration}" SOURCE_ROOT codemodel_source_root)
    _kontra_file_api_property("${project}" "${encoded_configuration}" BUILD_ROOT codemodel_build_root)

    # Collect files, compile settings, and Kbuild object lists from the reachable graph.
    foreach(target IN LISTS order)
        _kontra_read_target("${project}" "${encoded_configuration}" "${target}" target_json)
        _kontra_validate_compile_groups(target_json)
        set(group_indices)
        set(group_languages)
        set(group_flag_texts)
        _kontra_json_optional_indices(source_indices target_json sources)
        foreach(index IN LISTS source_indices)
            _kontra_json_get(source_record target_json sources "${index}")
            _kontra_json_get(path source_record path)
            _kontra_json_optional_get(generated source_record isGenerated)
            cmake_path(
                ABSOLUTE_PATH path
                BASE_DIRECTORY "${codemodel_source_root}"
                NORMALIZE
                OUTPUT_VARIABLE source
            )
            if(generated)
                _kontra_fail(
                    unsupported-generated-source
                    "source '${source}' is reported as GENERATED by the nested CMake project; build-time/generated-rule sources are not supported"
                )
            endif()

            _kontra_json_optional_get(group_index source_record compileGroupIndex)
            if(NOT group_index STREQUAL "")
                _kontra_path_within("${codemodel_build_root}" "${source}" source_in_build_tree ignored_relative)
                if(source_in_build_tree)
                    _kontra_record_backtrace_command(target_json source_record declaration_command)
                    if(declaration_command STREQUAL "")
                        _kontra_fail(
                            unsupported-generated-source
                            "compiled source '${source}' is synthesized by CMake in the nested build tree without declaration attribution; CMake-generated compilation units such as unity builds are not supported"
                        )
                    endif()
                endif()
            endif()

            if(IS_DIRECTORY "${source}")
                _kontra_fail(source-is-directory "target '${target}' lists directory '${source}' as a source")
            endif()
            if(NOT EXISTS "${source}" AND NOT IS_SYMLINK "${source}")
                _kontra_fail(
                    missing-projection-file
                    "declared file '${source}' does not exist after nested configuration"
                )
            endif()
            get_filename_component(source_extension "${source}" LAST_EXT)
            string(TOLOWER "${source_extension}" source_extension)
            if(source_extension STREQUAL ".o" OR source_extension STREQUAL ".obj")
                _kontra_fail(
                    unsupported-prebuilt-object
                    "prebuilt object source '${source}' is not supported"
                )
            endif()

            _kontra_projected_destination(
                "${project}" "${encoded_configuration}" "${source}" "${projection_root}" "${target}" source "${order}" destination
            )
            _kontra_claim_file("${source}" "${destination}" file_sources file_destinations)

            if(group_index STREQUAL "")
                continue()
            endif()
            list(FIND group_indices "${group_index}" cached_group_index)
            if(cached_group_index EQUAL -1)
                _kontra_compile_group(
                    "${project}" "${encoded_configuration}" target_json "${group_index}" "${projection_root}" "${order}"
                    language flags group_discarded_options
                )

                # The leading sentinel keeps an empty flag string in these parallel CMake lists. Without it, CMake
                # drops the empty element and the group_indices/languages/flag_texts rows no longer line up.
                if(flags)
                    list(JOIN flags " " flags_text)
                else()
                    set(flags_text)
                endif()
                set(cached_flags_text ".${flags_text}")

                list(APPEND group_indices "${group_index}")
                list(APPEND group_languages "${language}")
                _kontra_append_opaque_list_value(group_flag_texts "${cached_flags_text}")
                list(APPEND discarded_options ${group_discarded_options})
            else()
                list(GET group_languages "${cached_group_index}" language)
                list(GET group_flag_texts "${cached_group_index}" cached_flags_text)
                string(SUBSTRING "${cached_flags_text}" 1 -1 flags_text)
            endif()

            _kontra_source_language_info(
                "${language}" language_name language_extensions flag_variable suffix_requirement
            )
            get_filename_component(extension "${destination}" LAST_EXT)
            if(NOT extension IN_LIST language_extensions)
                _kontra_fail(
                    source-language-mismatch
                    "${language_name} source '${source}' ${suffix_requirement}"
                )
            endif()
            string(REGEX REPLACE "\\.[^.]+$" ".o" object "${destination}")
            if(object IN_LIST objects)
                _kontra_fail(object-path-collision "multiple sources map to Kbuild object '${object}'")
            endif()
            list(APPEND objects "${object}")
            if(NOT "${flags_text}" STREQUAL "")
                string(APPEND flag_lines "${flag_variable}_${object} += ${flags_text}\n")
            endif()
        endforeach()
    endforeach()

    if(NOT objects)
        _kontra_fail(module-has-no-compilation-units "module '${module}' has no C, C++, or assembly compilation units")
    endif()

    # Generate the static Kbuild files from the resolved CMake data.
    list(JOIN objects " " kontra_objects_text)
    set(kontra_module_name "${output_name}")
    set(kontra_object_flag_lines_text "${flag_lines}")
    _kontra_quote_kbuild_arguments("${kbuild_arguments}" kontra_kbuild_arguments_text)
    if(NOT kbuild_include STREQUAL "")
        set(kontra_user_kbuild_include "include $(src)/kontra-user.kbuild")
    else()
        set(kontra_user_kbuild_include)
    endif()

    set(templates_root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../templates")
    _kontra_read_template_body("${templates_root}/kbuild_compatibility.in" kontra_kbuild_compatibility)
    _kontra_read_template_body("${templates_root}/kbuild_linker.in" kontra_kbuild_linker)
    _kontra_read_template_body("${templates_root}/kbuild_toolchain.in" kontra_kbuild_toolchain)

    file(READ "${templates_root}/Kbuild.in" kbuild_template)
    string(CONFIGURE "${kbuild_template}" kbuild_content @ONLY)
    _kontra_write_if_different("${workspace}/Kbuild" "${kbuild_content}")
    file(READ "${templates_root}/Makefile.in" makefile_template)
    string(CONFIGURE "${makefile_template}" makefile_content @ONLY)
    _kontra_write_if_different("${workspace}/Makefile" "${makefile_content}")

    # Update the development projection symlinks and the manifest of files Kontraband created.
    set(owned_files "${file_destinations}")

    foreach(source destination IN ZIP_LISTS file_sources file_destinations)
        _kontra_ensure_symlink("${source}" "${workspace}/${destination}")
    endforeach()

    if(NOT kbuild_include STREQUAL "")
        set(destination kontra-user.kbuild)
        _kontra_ensure_symlink("${kbuild_include}" "${workspace}/${destination}")
        list(APPEND owned_files "${destination}")
    endif()

    _kontra_refresh_owned_files("${state_file}" "${workspace}" "${owned_files}")

    set("${out_sources}" "${file_sources}" PARENT_SCOPE)
    set("${out_destinations}" "${file_destinations}" PARENT_SCOPE)
    set("${out_discarded_options}" "${discarded_options}" PARENT_SCOPE)
endfunction()
